gxqpt:
  port:
    nginx: ${server.port}
    eureka: 10030
    gate: 10003    # 开发环境不使用nginx
  hostname:
    redis: 127.0.0.1
    rabbitmq: 127.0.0.1
    mysql: 127.0.0.1
    nginx: 127.0.0.1
    eureka: 127.0.0.1
    gate: 127.0.0.1      # 开发环境不使用nginx
    search: 127.0.0.1
  mysql:
    search:
      database: gxqpt_search_dev       # 根据环境更改
    port: 3306                  # 根据环境更改
    username: root              # 根据环境更改
    password: LLm65c0VVd3axid9u+Y7DZeKwcODMjU95FRhxom6ApE2yZ1kbi5YzSsdAIz+edUOZH3Engm17+NyfyNczpaYlw==
    admin:
      database: gxqpt_core_dev  # 根据环境更改
    exchange:
      database: gxqpt_exchange_dev # 根据环境更改

spring:
  profiles:
    active: dev
  rabbitmq:
    host: ${gxqpt.hostname.rabbitmq}     # 根据环境更改
    port: 5672               # 根据环境更改
    password: guest          # 根据环境更改
    username: guest          # 根据环境更改
  redis:
    host: ${gxqpt.hostname.redis}
    port: 6379
    key-prefix: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://${gxqpt.hostname.eureka}:${gxqpt.port.eureka}${gxqpt.context-path.eureka}/eureka/

id-generator:
  machine-code: 1  # id生成器机器掩码


Solr:
  zkHosts: 127.0.0.1:4180 #以逗号隔开多个zookeeper实例,如127.0.0.1:4180,127.0.0.1:4181
  #通过URL创建collection需要满足条件(numShards + numReplicas)< num（存活的节点数）,n根据实际部署的节点配置
  numShards: 1
  numReplicas: 1

