##################################################
# 注意:本地环境配置文件
# 这个配置文件中reids，rabbitmq，eureka等资源链接 本地
# 纯本地环境，所有的ip都是 127.0.0.1
##################################################
gxqpt:
  variable:
    gate-url: http://${gxqpt.hostname.gate}:${gxqpt.port.gate}   # 统一网关的链接前缀
  hostname:
    redis: 127.0.0.1         # 前端无需修改
    rabbitmq: 127.0.0.1   # 前端无需修改
    nginx: ${gxqpt.hostname.search}
    eureka: 192.168.1.204     # 根据自己环境修改
    gate: 192.168.1.111       # 网关的ip
    center: 127.0.0.1     # center的ip
    search: 192.168.1.111  # 权限系统ip [前端这里修改成自己的ip，不能是127.0.0.1/localhost]
  port:
    nginx: ${server.port}
    eureka: 10030
    gate: 10003
    center: 10086

sso:
  local-ip: ${gxqpt.hostname.search}
  local-port: ${server.port}
  server-ip: ${gxqpt.hostname.center}
  server-port: ${gxqpt.port.center}

spring:
  profiles:
    active: dev
  rabbitmq:
    port: 5672
    password: gxqpt
    username: gxqpt
  redis:
    port: 6379
    key-prefix: test

eureka:
  client:
    serviceUrl:
      defaultZone: http://${gxqpt.hostname.eureka}:${gxqpt.port.eureka}${gxqpt.context-path.eureka}/eureka/