##################################################
# 注意:开发环境配置文件
# 这个配置文件中reids，rabbitmq，eureka等资源链接测试服务器
# 这个配置文件一般适用于 前端开发
##################################################
gxqpt:
  variable:
    gate-url: http://${gxqpt.hostname.gate}:${gxqpt.port.gate}   # 统一网关的链接前缀
  hostname:
    redis: 192.168.1.204    # 前端无需修改
    rabbitmq: 192.168.1.204   # 前端无需修改
    nginx: ${gxqpt.hostname.modular}
    eureka: 192.168.1.204  #
    center: 192.168.1.204     # center的ip
    gate: 127.0.0.1     # 网关的ip
    modular: 192.168.1.92  # 根据自己环境修改
  port:
    nginx: 10086
    eureka: 10330
    gate: 10086
    center: 10086

sso:
  local-ip: ${gxqpt.hostname.modular}
  local-port: ${server.port}
  server-ip: ${gxqpt.hostname.center}
  server-port: ${gxqpt.port.center}

spring:
  profiles:
    active: dev
  rabbitmq:
    port: 5672
    password: gxqpt
    username: gxqpt
  redis:
    port: 16379
    key-prefix: test
    password: SbtyMveYNfLzTks7H0apCmyStPzWJqjy

eureka:
  client:
    serviceUrl:
      defaultZone: http://${gxqpt.hostname.eureka}:${gxqpt.port.eureka}${gxqpt.context-path.eureka}/eureka/