gxqpt:
  port:
    nginx: 10086
    eureka: 10030
    gate: ${gxqpt.port.nginx}        # 测试环境使用nginx
  hostname:
    redis: 192.168.0.53
    rabbitmq: 192.168.0.53
    mysql: 192.168.0.53
    nginx: 127.0.0.1
    eureka: 192.168.0.191
    gate: ${gxqpt.hostname.nginx}      # 测试环境使用nginx
    file: 192.168.0.191
  shareFileUrl: http://${gxqpt.hostname.nginx}:${gxqpt.port.nginx}/gxqpt-file/no/sharefile/
  mysql:
    file:
      database: gxqpt_file_test # 根据环境更改
    port: 3218                  # 根据环境更改
    username: root              # 根据环境更改
    password: LLm65c0VVd3axid9u+Y7DZeKwcODMjU95FRhxom6ApE2yZ1kbi5YzSsdAIz+edUOZH3Engm17+NyfyNczpaYlw==
  file:
    fastdfs:
      enabled: true
    upload-path-prefix: /home/gxqpt/uploadfile/file
    upload-path-temp: /home/gxqpt/uploadfile/temp
#    remote-uri-prefix: http://${gxqpt.hostname.nginx}:${gxqpt.port.nginx}/file/
    remote-uri-prefix: http://${gxqpt.hostname.nginx}:6080/
    ffmpeg-path: /usr/local/bin/ffmpeg
  swf-conver:
    env: 2
    swf-tools-path: /usr/local/swftools/bin/pdf2swf
    office-home: /opt/openoffice4
spring:
  profiles:
    active: test2
  rabbitmq:
    host: ${gxqpt.hostname.rabbitmq}     # 根据环境更改
    port: 5672               # 根据环境更改
    password: gxqpt          # 根据环境更改
    username: gxqpt          # 根据环境更改
  redis:
    host: ${gxqpt.hostname.redis}
    port: 16379
    key-prefix: test
    password: SbtyMveYNfLzTks7H0apCmyStPzWJqjy

eureka:
  client:
    serviceUrl:
      defaultZone: http://${gxqpt.hostname.eureka}:${gxqpt.port.eureka}${gxqpt.context-path.eureka}/eureka/

id-generator:
  machine-code: 1  # id生成器机器掩码