gxqpt:
  logs:
    app-id: 35kj6356
    app-secret: logs35kj6356
  port:
    nginx: ${server.port}
    eureka: 10030
    gate: ${gxqpt.port.nginx}
  hostname:
    redis: 127.0.0.1
    rabbitmq: 127.0.0.1
    mysql: 127.0.0.1
    nginx: 127.0.0.1
    eureka: 127.0.0.1
    gate: ${gxqpt.hostname.nginx}
    file: 127.0.0.1
    zipkin: 127.0.0.1
  context-path:
    eureka: /gxqpt-eureka
    gate: /api
  shareFileUrl: http://127.0.0.1:10005/gxqpt-file/no/sharefile/
  baiduImageDistinguish:
    api: https://aip.baidubce.com/rest/2.0/ocr/v1/general_basic     #图片文字识别接口
    tokenHost: https://aip.baidubce.com/oauth/2.0/token?           #token获取接口
    clientId: FwkigEdeCLykWplD5cu6mE02                             #API Key
    clientSecret: deYuB1x6buD2pA8RUt90SjLCIb0mj1Ir                #Securet Key
  mysql:
    file:
      database: gxqpt_file_dev       # 根据环境更改
      driverClassName: ${gxqpt.mysql.driverClassName}
      host: ${gxqpt.hostname.mysql}
      password: ${gxqpt.mysql.password}
      port: ${gxqpt.mysql.port}
      url: jdbc:mysql://${gxqpt.mysql.file.host}:${gxqpt.mysql.file.port}/${gxqpt.mysql.file.database}?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true
      username: ${gxqpt.mysql.username}
    driverClassName: com.mysql.jdbc.Driver
    port: 3306                  # 根据环境更改
    username: root              # 根据环境更改
    password: LLm65c0VVd3axid9u+Y7DZeKwcODMjU95FRhxom6ApE2yZ1kbi5YzSsdAIz+edUOZH3Engm17+NyfyNczpaYlw==
  file:
    fastdfs:
      enabled: false
    upload-path-prefix: /home/gxqpt/uploadfile/file
    ffmpeg-path: D:/ffmpeg/ffmpeg.exe
    remote-uri-prefix: http://192.168.65.147:6080/
    upload-path-temp: D:\home\gxqpt\uploadfile\temp
  swf-conver:
    env: 2
    swf-tools-path: /usr/local/swftools/bin/pdf2swf
    office-home: /opt/openoffice4
    xpdf-chinese-simplified: /usr/local/xpdf-chinese-simplified
    file-encode: UTF-8

logging:
  path: ./logs/gxqpt-file-server

dozer:
  mappingFiles: classpath*:dozer/*.dozer.xml

server:
  port: 10044
  context-path:
  undertow:
    io-threads: 4 # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    worker-threads: 80  # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    buffer-size: 1024  # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理 , 每块buffer的空间大小,越小的空间被利用越充分
    buffers-per-region: 1024  # 每个区分配的buffer数量 , 所以pool的大小是buffer-size * buffers-per-region
    direct-buffers: true  # 是否分配的直接内存

spring:
  application:
    name: gxqpt-file-server
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      max-file-size: 512Mb      # Max file size，默认1M
      max-request-size: 512Mb   # Max request size，默认10M
  profiles:
    active: dev
  rabbitmq:
    host: ${gxqpt.hostname.rabbitmq}
    port: 5672               # 根据环境更改
    password: guest          # 根据环境更改
    username: guest          # 根据环境更改
  redis:
    host: ${gxqpt.hostname.redis}
    port: 6379
    database: 1
    pool:
      max-active: 2
      min-idle: 1
      max-idle: 2
      max-wait: 60
    key-prefix: dev
  sleuth:
    sampler:
      percentage: 0  #采样率  采用率由网关去控制
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"
  zipkin:
    locator:
      discovery:
        enabled: true

eureka:
  instance:
    status-page-url-path: ${server.context-path}${management.context-path}/info
    health-check-url-path: ${server.context-path}${management.context-path}/health
    status-page-url: http://${gxqpt.hostname.gate}:${gxqpt.port.gate}${gxqpt.context-path.gate}/file${server.context-path}/swagger-ui.html
    preferIpAddress: true
    ip-address: ${gxqpt.hostname.file}
    instance-id: ${gxqpt.hostname.file}:${server.port}${server.context-path}
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
      management.context-path: ${management.context-path}
  client:
    serviceUrl:
      defaultZone: http://${gxqpt.hostname.eureka}:${gxqpt.port.eureka}${gxqpt.context-path.eureka}/eureka/

management:
  security:
    enabled: true
  context-path: ${server.context-path}/mgmt

security:
  basic:
    enabled: true
    path: ${management.context-path}
  user:
    name: admin
    password: gxqptadmin
endpoints:
  health:
    enabled: true
    sensitive: true  #actuator的health接口是否需要安全保证

hystrix:
  config:
    stream:
      maxConcurrentConnections: 50
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
  propagate:
    request-attribute:
      enabled: true
ribbon:
  eureka:
    enabled: true
#springfox:
#  documentation:
#    swagger:
#      v2.path: /v2/api-docs
#      v2.host: 127.0.0.1:10003
swagger2:
  file-map:
    title: 文件服务
    description: 高新区一体化平台项目，文件服务接口
    base-path: ${gxqpt.context-path.gate}/file
    impl-package: com.hengyunsoft.platform.file.impl
    open-package: com.hengyunsoft.platform.file.open
  logs-map:
    title: 日志服务
    description: 高新区一体化平台项目，日志服务接口
    base-path: ${gxqpt.context-path.gate}/logs
    impl-package: com.hengyunsoft.platform.logs.impl
    open-package: com.hengyunsoft.platform.logs.open
  contact-name: 中科恒运
  contact-url: http://www.hengyunsoft.com/
  contact-email: zkhy@hengyunsoft.com
  host: ${gxqpt.hostname.gate}:${gxqpt.port.gate}

auth:
  serviceId: gxqpt-auth-server
  app:
    token-header: token # 其三方应用token
    pub-key:
      path: app/pub.key
  client:
    id: gxqpt-file-server
    secret: 123456
    token-header: token
    admin-header: _isAdmin
    user-id: _user_id
    user-name: _user_name
    pub-key:
      path: client/pub.key

id-generator:
  machine-code: 1  # id生成器机器掩码

info:
  contact:
    email: xxx@hengyunsoft.com
  app: 文件服务

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

#日志管理系统文件保留默认设置
logs:
  keep:
    file: 180
    data: 180
    warn: 180
  runfile: /home/gxqpt/tempfolder  #配置临时文件存放路径。# linux       /home/gxqpt/tempfolder       window    d:/abc

#日志判断日志记录是否告警，一次推送数据条数
log:
  warning:
    total: 100
#ftp服务器信息
ftp:
  host: 192.168.0.191
  port: 0
  username: ftpUser
  password: 123
  basePath: /home/ftp  #linux中ftp服务器根目录 /home/ftpUser      window中配成斜线  /
  logAppId: 35kj6356
  logAppSecret: logs35kj6356
  serverUrl: http://192.168.0.191:10044