gxqpt:
  hostname:
    eureka: 127.0.0.1

server:
  port: 10030   # eureka 端口号
  context-path: /${spring.application.name}
logging:
  path: ./logs/gxqpt-eureka

spring:
  profiles:
    active: dev
  application:
    name: gxqpt-eureka

eureka:
  environment: ${spring.profiles.active}
  client:
    serviceUrl:
      defaultZone: http://${gxqpt.hostname.eureka}:10030${server.context-path}/eureka/
    registerWithEureka: false
    fetchRegistry: false
  instance:
    status-page-url-path: ${server.context-path}${management.context-path}/info
    health-check-url-path: ${server.context-path}${management.context-path}/health
    prefer-ip-address: true
    ip-address: ${gxqpt.hostname.eureka}
    instance-id: ${gxqpt.hostname.eureka}:${server.port}${server.context-path}
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
      management.context-path: ${management.context-path}

management:
  security:
    enabled: true
  context-path: /mgmt

security:
  basic:
    enabled: true
    path: ${management.context-path}
  user:
    name: admin
    password: gxqptadmin
endpoints:
  health:
    enabled: true
    sensitive: true  #actuator的health接口是否需要安全保证

info:
  contact:
    email: xxx@hengyunsoft.com
    phone: 10086
  app: 注册中心
  name: '@project.name@'
  description: "@project.description@"
  version: "@project.version@"
  spring-boot-version: "@spring.boot.version@"