spring:
  redis:
    host: 192.168.1.204
    port: 6379
    database: 2
    timeout: 5000
  data:
    redis:
      repositories:
        enabled: true
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gxqpt-core-test?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true
    username: root
    password: bNVOqb7WKLX5Bjnw+LMv92taj25KOxDimXxILPQjw42wgv+1lHzOH8kr97xDwWdhpY67QuYCS7sWN4W46YbkFA==
