###############################################################################
# 这个配置文件中的ip 和端口 禁止修改！！！（只能增加一些公共配置）
# 如需修改，请根据各自的环境，选择对应的配置文件进行修改。
###############################################################################

gxqpt:
  cas-server:
    ip: 127.0.0.1     # SSO CAS 服务的ip
    port: 10000       # SSO CAS 服务的端口
  variable:
    gate-url: http://${gxqpt.hostname.nginx}:${gxqpt.port.nginx}
    logout-url: ${cas.server.logout-url}
  port:
    nginx: 10086
    eureka: 10030
  hostname:
    redis: 127.0.0.1
    rabbitmq: 127.0.0.1
    nginx: 127.0.0.1
    eureka: 127.0.0.1       # eureka 的ip
    center: 127.0.0.1       # center 的ip
  center:
    app-id: 35kj6350
    app-secret: center35kj6350
    app-name: 系统综合平台
  feign:
    gate-server: gxqpt-gate-server
    auth-server: gxqpt-auth-server
  context-path:
    eureka: /gxqpt-eureka
    gate: /api
###############################################################################
# 下面的配置基本无差异
###############################################################################


############ cas client配置 开始 ############
#cas:
#  server:
#    login-url: http://${gxqpt.cas-server.ip}:${gxqpt.cas-server.port}/gxqpt-sso-webapp/login
#    logout-url: http://${gxqpt.cas-server.ip}:${gxqpt.cas-server.port}/gxqpt-sso-webapp/logout
#    validation-url: http://${gxqpt.cas-server.ip}:${gxqpt.cas-server.port}/gxqpt-sso-webapp
##    logout-notify-url: http://${gxqpt.hostname.center}:${server.port}
#    default-index: http://${gxqpt.hostname.center}:${server.port}${server.context-path}/admin/index
#  configure-key: casFlag
############ cas client配置 结束 ############

############ 多单点登录服务端 cas client配置 开始 ############
multiplecas:
  cas-configure:
    gxqpt:
      cas-server-login-url: http://${gxqpt.cas-server.ip}:${gxqpt.cas-server.port}/gxqpt-sso-webapp/login
      cas-server-url-logout: http://${gxqpt.cas-server.ip}:${gxqpt.cas-server.port}/gxqpt-sso-webapp/logout
      validation-cas-server-url-prefix: http://${gxqpt.cas-server.ip}:${gxqpt.cas-server.port}/gxqpt-sso-webapp
      default-sevice-name:  http://${gxqpt.hostname.center}:${server.port}${server.context-path}/admin/index
############ 多单点登录服务端 cas client配置 结束 ############


server:
  port: 10001
  context-path: /gxqpt-center

spring:
  application:
    name: gxqpt-center-webapp
  mvc:
    # #设定静态文件路径，js,css等
    static-path-pattern: /static/**
    view:
      suffix: .html
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    suffix: .html
    settings:
      number_format: 0.##       #解決freemarker数字输出中的逗号问题
      classic_compatible: true  #默认情况变量为null则替换为空字符串，如果需要自定义，写上${empty!"EmptyValue of fbysss"}的形式即可
      whitespace_stripping: true      # 剥离前后空字符串
      boolean_format: true,false      # 布尔类型格式化
      datetime_format: yyyy-MM-dd HH:mm:ss  # dateTime 类型格式化， 使用日期类型时， 需要在参数后追加 ?datetime eg: ${date?datetime}
      date_format: yyyy-MM-dd   # date 类型格式化， 使用日期类型时， 需要在参数后追加 ?date eg: ${date?date}
      time_format: HH:mm:ss      # time 类型格式化， 使用日期类型时， 需要在参数后追加 ?time eg: ${date?time}
      template_exception_handler: ignore   # 忽略模版异常
      default_encoding: UTF-8      # 默认编码
      url_escaping_charset: UTF-8  # url 转义编码
  rabbitmq:
    host: ${gxqpt.hostname.rabbitmq}
    password: guest
    port: 5672
    username: guest
  redis:
    host: ${gxqpt.hostname.redis}
    port: 6379
    database: 1
    pool:
      max-active: 2
      min-idle: 1
      max-idle: 2
      max-wait: 60
    key-prefix: dev
    biz-modular: gxqpt-center-webapp
  profiles:
    active: dev

management:
  security:
    enabled: true
  context-path: ${server.context-path}/mgmt
security:
  basic:
    enabled: true
    path: ${management.context-path}
  user:
    name: admin
    password: gxqptadmin
endpoints:
  health:
    enabled: true
    sensitive: true  #actuator的health接口是否需要安全保证

eureka:
  client:
    serviceUrl:
      defaultZone: http://${gxqpt.hostname.eureka}:${gxqpt.port.eureka}${gxqpt.context-path.eureka}/eureka/
  instance:
    status-page-url-path: ${server.context-path}${management.context-path}/info
    health-check-url-path: ${server.context-path}${management.context-path}/health
    status-page-url: http://${gxqpt.hostname.nginx}:${gxqpt.port.nginx}${server.context-path}/admin/index
    preferIpAddress: true
    ip-address: ${gxqpt.hostname.center}
    instance-id: ${gxqpt.hostname.center}:${server.port}${server.context-path}
    metadata-map:
      user.name: admin
      user.password: gxqptadmin
      management.context-path: ${management.context-path}

feign:
  hystrix:
    enabled: true
    #支持压缩的mime types
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
  propagate:
    request-attribute:
      enabled: true

ribbon:
  eureka:
    enabled: true
    
swagger2:
  sso-map:
    title: 高新区统一登录中心服务
    description: 高新区一体化平台项目，统一登录服务接口
    base-path: ${gxqpt.context-path.gate}/developer
    open-package: com.hengyunsoft.platform.controller.sso
  contact-name: 中科恒运
  contact-url: http://www.hengyunsoft.com/
  contact-email: zkhy@hengyunsoft.com
  host: ${gxqpt.hostname.gate}:${gxqpt.port.gate}
  
auth:
  serviceId: gxqpt-auth-server
  app:
    token-header: token # 其三方应用token
    pub-key:  # 服务端公钥路径
      path: app/pub.key
  client:
#    id: gxqpt-gate-server  #不填则默认读取spring.application.name
    secret: 123456
    token-header: token
    admin-header: _isAdmin
    user-id: _user_id
    user-name: _user_name
    pub-key: # 客服端公钥路径
      path: client/pub.key