gxqpt:
  cas-server:
    ip: ${gxqpt.hostname.nginx}             # SSO CAS 服务的ip
    port: ${gxqpt.port.nginx}         # SSO CAS 服务的端口
  port:
    nginx: 10086
  hostname:
    redis: 192.168.0.53
    rabbitmq: 192.168.0.53
    nginx: 127.0.0.1
    eureka: 192.168.0.191
    center: 192.168.0.53
  variable:
    gate-url: http://${gxqpt.hostname.nginx}:${gxqpt.port.nginx}

spring:
  profiles:
    active: test2
  rabbitmq:
    port: 5672
    password: gxqpt
    username: gxqpt
  redis:
    port: 16379
    key-prefix: test
    password: SbtyMveYNfLzTks7H0apCmyStPzWJqjy

multiplecas:
  cas-configure:
    gxqpt:
      casServerLoginUrl: http://${gxqpt.cas-server.ip}:${gxqpt.cas-server.port}/gxqpt-sso-webapp/login
      casServerUrlLogout: http://${gxqpt.cas-server.ip}:${gxqpt.cas-server.port}/gxqpt-sso-webapp/logout
      validationCasServerUrlPrefix: http://${gxqpt.cas-server.ip}:${gxqpt.cas-server.port}/gxqpt-sso-webapp
      defaultSeviceName: http://${gxqpt.hostname.nginx}:${gxqpt.port.nginx}${server.context-path}/admin/index
      casServerLogoutNotifyUrl: http://${gxqpt.hostname.center}:${server.port}
    sdzzww: 
      casServerLoginUrl: http://127.0.0.1:10086/gxqpt-sso-webapp/login
      casServerUrlLogout: http://127.0.0.1:10086/gxqpt-sso-webapp/logout
      validationCasServerUrlPrefix: http://127.0.0.1:10086/gxqpt-sso-webapp
      defaultSeviceName: http://${gxqpt.hostname.nginx}:${gxqpt.port.nginx}${server.context-path}/admin/index

eureka:
  client:
    serviceUrl:
      defaultZone: http://${gxqpt.hostname.eureka}:${gxqpt.port.eureka}${gxqpt.context-path.eureka}/eureka/
