gxqpt:
  hostname:
    rabbitmq: 127.0.0.1
    eureka: 127.0.0.1
    monitor: 127.0.0.1
  context-path:
    eureka: /gxqpt-eureka  # eureka的项目名

server:
  port: 10033
  context-path: /${spring.application.name}   # 监控系统项目名

turbine:
  stream:
    port: 10034

eureka:
  instance:
    status-page-url-path: ${server.context-path}${management.context-path}/info
    health-check-url-path: ${server.context-path}${management.context-path}/health
    status-page-url: http://${gxqpt.hostname.monitor}:${server.port}${server.context-path}
    prefer-ip-address: true
    ip-address: ${gxqpt.hostname.monitor}
    instance-id: ${gxqpt.hostname.monitor}:${server.port}${server.context-path}
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
      management.context-path: ${management.context-path}
  client:
    service-url:
      defaultZone: http://${gxqpt.hostname.eureka}:10030${gxqpt.context-path.eureka}/eureka/

logging:
  level:
    org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter: error
  path: ./logs/gxqpt-monitor

info:
  name: "@project.name@" #从pom.xml中获取
  description: "@project.description@"
  version: "@project.version@"
  spring-boot-version: "@project.parent.version@"


spring:
#  mail:
#    host: smtp.163.com
#    username: adadminfocus@163.com
#    password: adsugar123
#    properties:
#      smtp:
#        auth: true
#        starttls:
#          enable: true
#          required: true
  rabbitmq:
    port: 5672
    username: guest
    password: guest
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        location: http://${gxqpt.hostname.monitor}:${turbine.stream.port}${server.context-path}
  application:
    name: gxqpt-monitor
  profiles:
    active: dev

#      context-path: ${management.context-path}
#      notify:
#        mail:
#          to: tangyunhan@hengyunsoft.com
#          from: adadminfocus@163.com
#          ignore-changes: UNKNOWN:UP

#开启shutdown的安全验证
endpoints:
  cors:
    allowed-methods: HEAD,GET,POST
  health:
    enabled: true
    sensitive: true  #actuator的health接口是否需要安全保证

management:
  security:
    enabled: true
    roles: SUPERUSER
  context-path: /mgmt

security:
  basic:
    enabled: true
    path: ${server.context-path}${management.context-path}
  user:
    name: admin
    password: gxqptadmin

