gxqpt:
  port:
    nginx: 10086
    eureka: 10030
    gate: ${gxqpt.port.nginx}     # 测试环境使用nginx
  hostname:
    redis: 192.168.0.53
    rabbitmq: 192.168.0.53
    mysql: 192.168.0.53
    nginx: 127.0.0.1
    eureka: 192.168.0.191
    gate: ${gxqpt.hostname.nginx}     # 测试环境使用nginx
    exchange: 192.168.0.223
  mysql:
    exchange:
      database: gxqpt_exchange_test       # 根据环境更改
    port: 3218                  # 根据环境更改
    username: root              # 数据库密码需要加密： System.out.println(ConfigTools.encrypt("your mysql password"));
    password: LLm65c0VVd3axid9u+Y7DZeKwcODMjU95FRhxom6ApE2yZ1kbi5YzSsdAIz+edUOZH3Engm17+NyfyNczpaYlw==

spring:
  profiles:
    active: test2
  rabbitmq:
    host: ${gxqpt.hostname.rabbitmq}
    port: 5672               # 根据环境更改
    password: gxqpt          # 根据环境更改
    username: gxqpt          # 根据环境更改
  redis:
    host: ${gxqpt.hostname.redis}
    port: 16379
    key-prefix: test
    password: SbtyMveYNfLzTks7H0apCmyStPzWJqjy

eureka:
  client:
    serviceUrl:
      defaultZone: http://${gxqpt.hostname.eureka}:${gxqpt.port.eureka}${gxqpt.context-path.eureka}/eureka/

id-generator:
  machine-code: 1  # id生成器机器掩码


jdbc:
  port: 3218
  ip: 192.168.0.53
  userName: root
  pwd: r!o@o#t$>?.123
  dbName: gxqpt_data_warehouse

app:
  id: 35kj6100
  name: 共享交换系统