##################################################
# 注意: 测试环境配置文件
# 这个配置文件中reids，rabbitmq，eureka等资源链接测试服务器
##################################################
gxqpt:
  variable:
    gate-url: http://${gxqpt.hostname.nginx}:${gxqpt.port.nginx}   # 统一网关的链接前缀
  hostname:
    redis: 192.168.0.53
    rabbitmq: 192.168.0.53
    nginx: 127.0.0.1     # 根据自己环境修改
    eureka: 192.168.0.191     # 根据自己环境修改
    center: 192.168.0.53       # 根据自己环境修改
    gate: 192.168.0.191     # 根据自己环境修改
    logs: 192.168.0.194  # 根据自己环境修改
  port:
    nginx: 10086
    eureka: 10030
    gate: 10003
    center: 10001

sso:
  local-ip: ${gxqpt.hostname.nginx}       # 本机的ip [前端 修改成自己的ip，不能是127.0.0.1/localhost]
  local-port: ${gxqpt.port.nginx}           #
  server-ip: ${gxqpt.hostname.nginx}      # center-webapp 的ip
  server-port: ${gxqpt.port.nginx}  # center-webapp 的ip

spring:
  profiles:
    active: test2
  rabbitmq:
    port: 5672
    password: gxqpt
    username: gxqpt
  redis:
    port: 16379
    key-prefix: test
    password: SbtyMveYNfLzTks7H0apCmyStPzWJqjy

eureka:
  client:
    serviceUrl:
      defaultZone: http://${gxqpt.hostname.eureka}:${gxqpt.port.eureka}${gxqpt.context-path.eureka}/eureka/
