##################################################
# 注意:开发环境配置文件
# 这个配置文件中reids，rabbitmq，eureka等资源链接测试服务器
# 这个配置文件一般适用于 前端开发
##################################################
gxqpt:
  variable:
    gate-url: http://${gxqpt.hostname.gate}:10086   # 统一网关的链接前缀
  hostname:
    redis: 127.0.0.1      # 前端无需修改
    rabbitmq: 127.0.0.1    #
    nginx: ${gxqpt.hostname.logs}
    eureka: 192.168.1.204     #
    gate: 127.0.0.1      # 网关的ip
    center: 127.0.0.1     #  [前端这里修改成自己启动的center的ip，不能是127.0.0.1/localhost]
    logs: 192.168.1.92       # [前端这里修改成自己的ip，不能是127.0.0.1/localhost]
  port:
    nginx: ${server.port}
    eureka: 10030
    gate: 10003
    center: 10086

sso:
  local-ip: ${gxqpt.hostname.logs}
  local-port: ${server.port}
  server-ip: ${gxqpt.hostname.center}
  server-port: ${gxqpt.port.center}


spring:
  profiles:
    active: dev
  rabbitmq:
    port: 5672
    password: guest
    username: guest
  redis:
    port: 16379
    key-prefix: test
    password: SbtyMveYNfLzTks7H0apCmyStPzWJqjy

eureka:
  client:
    serviceUrl:
      defaultZone: http://${gxqpt.hostname.eureka}:${gxqpt.port.eureka}${gxqpt.context-path.eureka}/eureka/