gxqpt:
  port:
    nginx: ${server.port}
    eureka: 10030
    gate: ${gxqpt.port.nginx}
  hostname:
    redis: 127.0.0.1
    rabbitmq: 127.0.0.1
    mysql: 127.0.0.1
    nginx: 127.0.0.1
    eureka: 127.0.0.1
    gate: ${gxqpt.hostname.nginx}
    mt: 127.0.0.1
  context-path:
    eureka: /gxqpt-eureka
    gate: /api
  hardware-webapp:  # 系统的appid 跟服务的不同！ 特别注意！
    app-id: 45aj6316
    app-secret: hardware45aj6316
  mt-webapp:
    app-id: 45aj6314
    app-secret: mt45aj6314
  ops-webapp:
    app-id: 45aj6317
    app-secret: ops45aj6317
    app-name: 运维管理平台
  security-webapp:
    app-id: 45aj6315
    app-secret: security45aj6315
  warnconstat:
    channel_id: 888 #  短信发送渠道id
    template_id: 644693885025 # 短信模板id

  mysql:
    mt:
      database: gxqpt_pt_dev       # 根据环境更改
      driverClassName: ${gxqpt.mysql.driverClassName}
      host: ${gxqpt.hostname.mysql}
      password: ${gxqpt.mysql.password}
      port: ${gxqpt.mysql.port}
      url: jdbc:mysql://${gxqpt.mysql.mt.host}:${gxqpt.mysql.mt.port}/${gxqpt.mysql.mt.database}?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true
      username: ${gxqpt.mysql.username}
    driverClassName: com.mysql.jdbc.Driver
    port: 3306                  # 根据环境更改
    username: root              # 根据环境更改
    password: bNVOqb7WKLX5Bjnw+LMv92taj25KOxDimXxILPQjw42wgv+1lHzOH8kr97xDwWdhpY67QuYCS7sWN4W46YbkFA==


logging:
  path: ./logs/gxqpt-pt-server
  level:
    com.hengyunsoft.platform.developer.api.core.api: debug
    com.hengyunsoft.platform.msgs.open.msg: debug
dozer:
  mappingFiles: classpath*:dozer/*.dozer.xml

server:
  port: 10052
  context-path:
  undertow:
    io-threads: 4 # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    worker-threads: 80  # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    buffer-size: 1024  # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理 , 每块buffer的空间大小,越小的空间被利用越充分
    buffers-per-region: 1024  # 每个区分配的buffer数量 , 所以pool的大小是buffer-size * buffers-per-region
    direct-buffers: true  # 是否分配的直接内存

spring:
  application:
    name: gxqpt-pt-server
  profiles:
    active: dev
  rabbitmq:
    host: ${gxqpt.hostname.rabbitmq}
    port: 5672               # 根据环境更改
    password: guest          # 根据环境更改
    username: guest          # 根据环境更改
  redis:
    host: ${gxqpt.hostname.redis}
    port: 6379
    database: 1
    pool:
      max-active: 2
      min-idle: 1
      max-idle: 2
      max-wait: 60
    key-prefix: dev
  sleuth:
    sampler:
      percentage: 0  #采样率  采用率由网关去控制
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"
  zipkin:
    locator:
      discovery:
        enabled: true

eureka:
  instance:
    status-page-url-path: ${server.context-path}${management.context-path}/info
    health-check-url-path: ${server.context-path}${management.context-path}/health
    status-page-url: http://${gxqpt.hostname.gate}:${gxqpt.port.gate}${gxqpt.context-path.gate}/mt${server.context-path}/swagger-ui.html
    preferIpAddress: true
    ip-address: ${gxqpt.hostname.mt}
    instance-id: ${gxqpt.hostname.mt}:${server.port}${server.context-path}
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
      management.context-path: ${management.context-path}
  client:
    serviceUrl:
      defaultZone: http://${gxqpt.hostname.eureka}:${gxqpt.port.eureka}${gxqpt.context-path.eureka}/eureka/

management:
  security:
    enabled: true
  context-path: ${server.context-path}/mgmt

security:
  basic:
    enabled: true
    path: ${management.context-path}
  user:
    name: admin
    password: gxqptadmin
endpoints:
  health:
    enabled: true
    sensitive: true  #actuator的health接口是否需要安全保证

hystrix:
  config:
    stream:
      maxConcurrentConnections: 50
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
  propagate:
    request-attribute:
      enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

swagger2:
  mt-map:
    title: 高新区移动端服务
    description: 高新区一体化平台项目，高新区移动端服务
    base-path: ${gxqpt.context-path.gate}/mt
    impl-package: com.hengyunsoft.platform.mt.impl
    open-package: com.hengyunsoft.platform.mt.open
  security-map:
    title: 安全保障服务
    description: 高新区一体化平台项目，安全保障服务
    base-path: ${gxqpt.context-path.gate}/security
    impl-package: com.hengyunsoft.platform.security.impl
    open-package: com.hengyunsoft.platform.security.open
  hardware-map:
    title: 软硬件管理服务
    description: 高新区一体化平台项目，软硬件管理服务
    base-path: ${gxqpt.context-path.gate}/hardware
    impl-package: com.hengyunsoft.platform.hardware.impl
  ops-map:
    title: 运维管理服务
    description: 高新区一体化平台项目，运维管理服务
    base-path: ${gxqpt.context-path.gate}/ops
    impl-package: com.hengyunsoft.platform.ops.impl
  contact-name: 中科恒运
  contact-url: http://www.hengyunsoft.com/
  contact-email: zkhy@hengyunsoft.com
  host: ${gxqpt.hostname.gate}:${gxqpt.port.gate}

auth:
  serviceId: gxqpt-auth-server
  app:
    token-header: token # 其三方应用token
    pub-key:
      path: app/pub.key
  client:
    id: gxqpt-pt-server
    secret: 123456
    token-header: token
    admin-header: _isAdmin
    user-id: _user_id
    user-name: _user_name
    pub-key:
      path: client/pub.key

id-generator:
  machine-code: 1  # id生成器机器掩码

info:
  contact:
    email: xxx@hengyunsoft.com
  app: 文件服务

#文件上传下载
fileServerUrl: http://${gxqpt.hostname.nginx}:${gxqpt.port.nginx}
#登录地址
loginUrl: http://${gxqpt.hostname.nginx}:10086/api/auth/p/login
#getToeknPre: "test:gxqpt-auth-server:app:token:"
#mt:
#  app-id: 45aj6314
#  app-secret: mt45aj6314
#最新apk下载地址
apkDownUrl: http://${gxqpt.hostname.nginx}:${gxqpt.port.nginx}/apk